### ISSUE TITLE
能加入昵称作为标识区分吗

### ISSUE THREAD

**Issue by axlmly** [lgc-KoiDev/koishi-plugin-isekai-tensei#1]
以及是否有打算增加更多的可随机特质。

**Comment by axlmly** [comment]
以及世界设定的开局和审美反了

**Comment by lgc2333** [comment]
特质的话我把原贴的东西都做进来了来着
开局审美反晚点修
昵称作为标识区分指的是？在图片中加入触发者昵称吗

**Comment by axlmly** [comment]
> 特质的话我把原贴的东西都做进来了来着
> 开局审美反晚点修
> 昵称作为标识区分指的是？在图片中加入触发者昵称吗

是的，或许可以在种子下面加入触发者昵称。

**Comment by axlmly** [comment]
> 特质的话我把原贴的东西都做进来了来着 开局审美反晚点修 昵称作为标识区分指的是？在图片中加入触发者昵称吗

随机特质图片这块我可以参与吗,如果有打算增加的话.
![断钢圣剑模板](https://github.com/lgc2333/koishi-plugin-isekai-tensei/assets/41771421/d1fa0217-8837-4131-bfba-28451b0e9e08)

**Comment by lgc2333** [comment]
目前我是打算只内置原图的东西，将来或许可以做加载外置属性

**Comment by lgc2333** [comment]
https://www.npmjs.com/package/koishi-plugin-isekai-tensei/v/0.1.4
